# -*- coding: utf-8 -*-

"""
/***************************************************************************
 TGVLoadCorrectionData
                                 A QGIS plugin
 QGIS processing plugin to load temporal correction data for hydrological 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-24
        copyright            : (C) 2026 by Bo Victor Thomsen AestasGIS Denmark
        email                : bvt@aestas.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Bo Victor Thomsen, AestasGIS Denmark'
__date__ = '2026-03-24'
__copyright__ = '(C) 2026 by Bo Victor Thomsen, AestasGIS Denmark'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

TEMPLATE = """
INSERT INTO tgv_data.tgv_buildings 
        (building_id,municipality_code,build_usage_code,build_area_m2,build_perimeter_m,cellar_area_m2,cellar_perimeter_m,is_protected,geom)
    SELECT 
        building_id,municipality_code,build_usage_code,build_area_m2,build_perimeter_m,cellar_area_m2,cellar_perimeter_m,is_protected,ST_Force2D(geom)
    FROM tgv_import.{0} 
    ON CONFLICT ON CONSTRAINT tgv_buildings_pkey DO 
        UPDATE SET (municipality_code,build_usage_code,build_area_m2,build_perimeter_m,cellar_area_m2,cellar_perimeter_m,is_protected,geom) = 
        (EXCLUDED.municipality_code,EXCLUDED.build_usage_code,EXCLUDED.build_area_m2,EXCLUDED.build_perimeter_m,EXCLUDED.cellar_area_m2,
        EXCLUDED.cellar_perimeter_m,EXCLUDED.is_protected,EXCLUDED.geom); 
DROP TABLE tgv_import.{0};
"""

from typing import Any, Optional

from qgis.core import QgsProcessing
from qgis.core import QgsProcessingAlgorithm
from qgis.core import QgsProcessingContext
from qgis.core import QgsProcessingFeedback, QgsProcessingMultiStepFeedback
from qgis.core import QgsProcessingParameterString
from qgis.core import QgsProcessingParameterProviderConnection
from qgis.core import QgsProcessingParameterVectorLayer
from qgis.core import QgsProcessingParameterBand
from qgis.core import QgsProcessingParameterEnum
from qgis.core import QgsProcessingParameterNumber
from qgis.core import QgsProcessingParameterFeatureSink
from qgis.core import QgsExpression
from qgis import processing


class TGVLoadBuildingData(QgsProcessingAlgorithm):

    def initAlgorithm(self, config: Optional[dict[str, Any]] = None):
        self.addParameter(QgsProcessingParameterProviderConnection('database_connection', 'Database connection', 'postgres', defaultValue=None))
        self.addParameter(QgsProcessingParameterVectorLayer('building_layer', 'Building layer', types=[QgsProcessing.TypeVectorPolygon], defaultValue=None))
        self.addParameter(QgsProcessingParameterEnum('input_format', 'Input format', options=['Envidan','Other'], allowMultiple=False, usesStaticStrings=False, defaultValue=0))

#        self.addParameter(QgsProcessingParameterFeatureSink('refactor', 'Refactor', type=QgsProcessing.TypeVectorAnyGeometry, createByDefault=True, supportsAppend=True, defaultValue=None))

    def processAlgorithm(self, parameters: dict[str, Any], context: QgsProcessingContext, model_feedback: QgsProcessingFeedback) -> dict[str, Any]:
        feedback = QgsProcessingMultiStepFeedback(10, model_feedback)
        results = {}
        outputs = {}

        # Calculate expression
        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}

        alg_params = {
            'INPUT': QgsExpression("'t_' || replace(uuid('WithoutBraces'),'-','')").evaluate()
        }
        outputs['CalculateExpression'] = processing.run('native:calculateexpression', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        # Temp variables, translation of parameters
        formats = ['Envidan','Other']
        format = formats[parameters['input_format']]

        # PostgreSQL execute and load SQL(reference only)

        #conns = QgsProviderRegistry.instance().providerMetadata('postgres').connections(False)
        #dbCon = conns[parameters['database_connection']]
        #res = dbCon.executeSql("SELECT ST_AsText(geom) AS wkt FROM tgv_data.tgv_projects WHERE project_id = '{}'".format( parameters['project_name']))
        #wkt = res[0][0]

        #temp = QgsVectorLayer("Polygon?crs=epsg:25832", "temp", "memory")
        #dp_temp = temp.dataProvider()
        #geom = QgsGeometry.fromWkt(wkt)
        #feat = QgsFeature()
        #feat.setGeometry(geom)
        #dp_temp.addFeatures([feat])

        feedback.setCurrentStep(2)
        if feedback.isCanceled():
            return {}

        if format == 'Envidan':

            # Refactor fields
            alg_params = {
                'FIELDS_MAPPING': [{'alias': '','comment': '','expression': '"bbruuid"','length': -1,'name': 'building_id','precision': 0,'sub_type': 0,'type': 10,'type_name': 'text'},{'alias': '','comment': '','expression': '0','length': -1,'name': 'municipality_code','precision': 0,'sub_type': 0,'type': 2,'type_name': 'integer'},{'alias': '','comment': '','expression': '0','length': -1,'name': 'build_usage_code','precision': 0,'sub_type': 0,'type': 2,'type_name': 'integer'},{'alias': '','comment': '','expression': '"byg041Beby"','length': -1,'name': 'build_area_m2','precision': 0,'sub_type': 0,'type': 6,'type_name': 'double precision'},{'alias': '','comment': '','expression': 'round(perimeter (@geometry),2)','length': -1,'name': 'build_perimeter_m','precision': 0,'sub_type': 0,'type': 6,'type_name': 'double precision'},{'alias': '','comment': '','expression': 'max(coalesce("Kaelderare",0), coalesce("Kaelderar_",0))','length': -1,'name': 'cellar_area_m2','precision': 0,'sub_type': 0,'type': 6,'type_name': 'double precision'},{'alias': '','comment': '','expression': 'if (max(coalesce("Kaelderare",0), coalesce("Kaelderar_",0)) > 0.0, \r\n0.0000001 * max(coalesce("Kaelderare",0), coalesce("Kaelderar_",0))^3 -\r\n0.0002    * max(coalesce("Kaelderare",0), coalesce("Kaelderar_",0))^2 +\r\n0.1525    * max(coalesce("Kaelderare",0), coalesce("Kaelderar_",0))+ 5.4434,\r\n0.0) ','length': -1,'name': 'cellar_perimeter_m','precision': 0,'sub_type': 0,'type': 6,'type_name': 'double precision'},{'alias': '','comment': '','expression': 'max(coalesce("byg026Opfo",1000),coalesce("byg027OmTi",1000)) >= 1973','length': -1,'name': 'is_protected','precision': 0,'sub_type': 0,'type': 1,'type_name': 'boolean'}],
                'INPUT': parameters['building_layer'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
#                'OUTPUT': parameters['refactor']
            }
            outputs['RefactorFields'] = processing.run('native:refactorfields', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        else: 
            feedback.pushInfo('*** Input format not known !, stopping... ' + format)
            return {}
    
        feedback.setCurrentStep(3)
        if feedback.isCanceled():
            return {}

        # Export to PostgreSQL
        alg_params = {
            'CREATEINDEX': True,
            'DATABASE': parameters['database_connection'],
            'DROP_STRING_LENGTH': False,
            'ENCODING': 'UTF-8',
            'FORCE_SINGLEPART': True,
            'GEOMETRY_COLUMN': 'geom',
            'INPUT': outputs['RefactorFields']['OUTPUT'],
            'LOWERCASE_NAMES': True,
            'OVERWRITE': True,
            'PRIMARY_KEY': 'id',
            'SCHEMA': 'tgv_import',
            'TABLENAME': outputs['CalculateExpression']['OUTPUT']
        }
        outputs['ExportToPostgresql'] = processing.run('native:importintopostgis', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(4)
        if feedback.isCanceled():
            return {}
            
        # PostgreSQL execute SQL
        alg_params = {
            'DATABASE': parameters['database_connection'],
            'SQL': TEMPLATE.format(outputs['CalculateExpression']['OUTPUT'])
        }
        outputs['PostgresqlExecuteSql'] = processing.run('native:postgisexecutesql', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        return results

    def name(self) -> str:
        return 'terrain_groundwater_load_building_data'

    def displayName(self) -> str:
        return 'OS2 Terrain Groundwater load building data'

    def group(self) -> str:
        return ''

    def groupId(self) -> str:
        return ''

    def createInstance(self):
        return self.__class__()

