# -*- coding: utf-8 -*-

"""
/***************************************************************************
 TGVInterpolateCellValues
                                 A QGIS plugin
 QGIS processing plugin to interpolate cell values from org measurements for hydrological 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-17
        copyright            : (C) 2026 by Bo Victor Thomsen AestasGIS Denmark
        email                : bvt@aestas.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Bo Victor Thomsen, AestasGIS Denmark'
__date__ = '2026-04-17'
__copyright__ = '(C) 2026 by Bo Victor Thomsen, AestasGIS Denmark'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

TEMPLATE = """
SELECT tgv_functions.models_interpolate_cell_values('{0}','{1}');
"""
TEMPLATE2 = """
SELECT tgv_functions.models_create_cell_calculations('{0}','{1}',{2});
"""
TEMPLATE3 = """
SELECT tgv_functions.building_costs_calculate('{0}','{1}');
"""

from typing import Any, Optional

from qgis.core import QgsProcessing
from qgis.core import QgsProcessingAlgorithm
from qgis.core import QgsProcessingContext
from qgis.core import QgsProcessingFeedback, QgsProcessingMultiStepFeedback
from qgis.core import QgsProcessingParameterString
from qgis.core import QgsProcessingParameterProviderConnection
from qgis.core import QgsProcessingParameterRasterLayer
from qgis.core import QgsProcessingParameterBand
from qgis.core import QgsProcessingParameterEnum
from qgis.core import QgsProcessingParameterNumber
from qgis.core import QgsProcessingParameterBoolean
from qgis.core import QgsProcessingParameterFeatureSink
from qgis.core import QgsProcessingParameterDefinition
from qgis.core import QgsExpression
from qgis import processing


class TGVInterpolateCellValues(QgsProcessingAlgorithm):

    def initAlgorithm(self, config: Optional[dict[str, Any]] = None):
        self.addParameter(QgsProcessingParameterProviderConnection('database_connection', 'Database connection', 'postgres', defaultValue=None))
        self.addParameter(QgsProcessingParameterString('project_name', 'Project name', multiLine=False, defaultValue=None))
        self.addParameter(QgsProcessingParameterString('model_name', 'Model name', multiLine=False, defaultValue=None))
        param = QgsProcessingParameterBoolean('mut1_excludes_mut2', 'Does mut1 exclude mut2 days', defaultValue=False)
        param.setFlags(param.flags() | QgsProcessingParameterDefinition.FlagAdvanced)
        self.addParameter(param)


    def processAlgorithm(self, parameters: dict[str, Any], context: QgsProcessingContext, model_feedback: QgsProcessingFeedback) -> dict[str, Any]:
        # Use a multi-step feedback, so that individual child algorithm progress reports are adjusted for the
        # overall progress through the model
        feedback = QgsProcessingMultiStepFeedback(3, model_feedback)
        results = {}
        outputs = {}

        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}
        # PostgreSQL execute SQL
        sqlTxt = TEMPLATE.format(parameters['project_name'],parameters['model_name'])
        feedback.pushInfo('Step 1: Interpolate future depths for cells, SQL: ' +  sqlTxt)
        alg_params = {
            'DATABASE': parameters['database_connection'],
            'SQL': sqlTxt
        }
        outputs['PostgresqlExecuteSql'] = processing.run('native:postgisexecutesql', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(2)
        if feedback.isCanceled():
            return {}
        # PostgreSQL execute SQL
        sqlTxt = TEMPLATE2.format(parameters['project_name'],parameters['model_name'],parameters['mut1_excludes_mut2'])
        feedback.pushInfo('Step 2: Interpolate costs on cell basis, SQL: ' +  sqlTxt)
        alg_params = {
            'DATABASE': parameters['database_connection'],
            'SQL': sqlTxt
        }
        outputs['PostgresqlExecuteSql2'] = processing.run('native:postgisexecutesql', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(3)
        if feedback.isCanceled():
            return {}
        # PostgreSQL execute SQL
        sqlTxt = TEMPLATE3.format(parameters['project_name'],parameters['model_name'])
        feedback.pushInfo('Step 3: Interpolate costs on buildings basis, SQL: ' +  sqlTxt)
        alg_params = {
            'DATABASE': parameters['database_connection'],
            'SQL': sqlTxt
        }
        outputs['PostgresqlExecuteSql3'] = processing.run('native:postgisexecutesql', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        return results

    def name(self) -> str:
        return 'terrain_groundwater_interpolate_cell_values'

    def displayName(self) -> str:
        return 'OS2 Terrain Groundwater interpolate cell values'

    def group(self) -> str:
        return ''

    def groupId(self) -> str:
        return ''

    def createInstance(self):
        return self.__class__()

