# -*- coding: utf-8 -*-

"""
/***************************************************************************
 TGVLoadDepthData
                                 A QGIS plugin
 QGIS processing plugin to load temporal correction data for hydrological 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-24
        copyright            : (C) 2026 by Bo Victor Thomsen AestasGIS Denmark
        email                : bvt@aestas.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Bo Victor Thomsen, AestasGIS Denmark'
__date__ = '2026-03-24'
__copyright__ = '(C) 2026 by Bo Victor Thomsen, AestasGIS Denmark'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
from typing import Any, Optional
from qgis.core import QgsProcessing
from qgis.core import QgsProcessingAlgorithm
from qgis.core import QgsProcessingContext
from qgis.core import QgsProcessingFeedback, QgsProcessingMultiStepFeedback
from qgis.core import QgsProcessingParameterFileDestination
from qgis.core import QgsProcessingParameterFile
from qgis.core import QgsProcessingParameterProviderConnection
from qgis.core import QgsProviderRegistry
from qgis.core import QgsDataSourceUri
from qgis import processing
class TGVCreateQgisProject(QgsProcessingAlgorithm):

    def initAlgorithm(self, config: Optional[dict[str, Any]] = None):
        self.addParameter(QgsProcessingParameterProviderConnection('database_connection', 'Database connection', 'postgres', defaultValue=None))
        self.addParameter(QgsProcessingParameterFileDestination  ('qgis_project_file', 'QGIS project file', fileFilter='QGIS projects (*.qgs,*.QGS)', defaultValue=None))


    def processAlgorithm(self, parameters: dict[str, Any], context: QgsProcessingContext, model_feedback: QgsProcessingFeedback) -> dict[str, Any]:
        # Use a multi-step feedback, so that individual child algorithm progress reports are adjusted for the
        # overall progress through the model
        feedback = QgsProcessingMultiStepFeedback(2, model_feedback)
        results = {}
        outputs = {}

        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}

        # Convert connection to specific parameters
        conns = QgsProviderRegistry.instance().providerMetadata('postgres').connections(False)
        dbCon = conns[parameters['database_connection']]
        dbUri = QgsDataSourceUri(dbCon.uri())

        hostname = dbUri.host()
        portno = dbUri.port() 
        username = dbUri.username()
        password = dbUri.password()
        dbname = dbUri.database()
         
        # Fetch procject template
        plugin_dir = os.path.dirname(__file__)
        qgis_tgv_template = os.path.join(plugin_dir,'templates','tgv_projects.template.qgs')

        feedback.setCurrentStep(2)
        if feedback.isCanceled():
            return {}
            
        with open(qgis_tgv_template, 'r') as tfile:
            template = tfile.read()
            project = template.format(hostname=hostname,portno=portno,username=username,password=password,dbname=dbname)
            with open(parameters['qgis_project_file'], "w") as qgis_project:
                qgis_project.write(project)

        feedback.pushInfo('Ending... ')
        return results

    def name(self) -> str:
        return 'terrain_groundwater_create_qgis_project'

    def displayName(self) -> str:
        return 'OS2 Terrain Groundwater create QGIS project'

    def group(self) -> str:
        return ''

    def groupId(self) -> str:
        return ''

    def createInstance(self):
        return self.__class__()

