# -*- coding: utf-8 -*-

"""
/***************************************************************************
 TGVLoadCorrectionData
                                 A QGIS plugin
 QGIS processing plugin to load temporal correction data for hydrological 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-24
        copyright            : (C) 2026 by Bo Victor Thomsen AestasGIS Denmark
        email                : bvt@aestas.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Bo Victor Thomsen, AestasGIS Denmark'
__date__ = '2026-03-24'
__copyright__ = '(C) 2026 by Bo Victor Thomsen, AestasGIS Denmark'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

TEMPLATE = """
INSERT INTO tgv_data.tgv_corrections 
    SELECT project_id, season, id, depth, geom FROM tgv_import.{0} 
    ON CONFLICT ON CONSTRAINT tgv_corrections_pkey DO 
        UPDATE SET (geom,depth) = (EXCLUDED.geom,EXCLUDED.depth); 
--DROP TABLE tgv_import.{0};
"""

TEMPLATE2 = """
SELECT tgv_functions.cells_update_from_corrections('{0}',{1},'{2}');
"""
TEMPLATE3 = "SELECT ST_AsText(ST_Buffer(geom,{1})) AS wkt FROM tgv_data.tgv_projects WHERE project_id = '{0}'"

from typing import Any, Optional

from qgis.core import QgsProcessing
from qgis.core import QgsProcessingAlgorithm
from qgis.core import QgsProcessingContext
from qgis.core import QgsProcessingFeedback, QgsProcessingMultiStepFeedback
from qgis.core import QgsProcessingParameterString
from qgis.core import QgsProcessingParameterProviderConnection
from qgis.core import QgsProcessingParameterRasterLayer
from qgis.core import QgsProcessingParameterBand
from qgis.core import QgsProcessingParameterEnum
from qgis.core import QgsProcessingParameterNumber
from qgis.core import QgsProcessingParameterFeatureSink
from qgis.core import QgsProviderRegistry
from qgis.core import QgsVectorLayer
from qgis.core import QgsGeometry
from qgis.core import QgsFeature
from qgis.core import QgsExpression
from qgis import processing


class TGVLoadCorrectionData(QgsProcessingAlgorithm):

    def initAlgorithm(self, config: Optional[dict[str, Any]] = None):
        self.addParameter(QgsProcessingParameterProviderConnection('database_connection', 'Database connection', 'postgres', defaultValue=None))
        self.addParameter(QgsProcessingParameterString('project_name', 'Project name', multiLine=False, defaultValue=None))
        self.addParameter(QgsProcessingParameterNumber('cell_size', 'Cell size', type=QgsProcessingParameterNumber.Double, minValue=5, maxValue=1000, defaultValue=100))
        self.addParameter(QgsProcessingParameterRasterLayer('spring_correction_layer', 'Spring Correction layer', defaultValue=None))
        self.addParameter(QgsProcessingParameterBand('spring_correction_band', 'Spring Correction band', parentLayerParameterName='spring_correction_layer', allowMultiple=False, defaultValue=1))
        self.addParameter(QgsProcessingParameterRasterLayer('summer_correction_layer', 'Summer Correction layer', defaultValue=None))
        self.addParameter(QgsProcessingParameterBand('summer_correction_band', 'Summer Correction band', parentLayerParameterName='summer_correction_layer', allowMultiple=False, defaultValue=1))
        self.addParameter(QgsProcessingParameterRasterLayer('autumn_correction_layer', 'Autumn Correction layer', defaultValue=None))
        self.addParameter(QgsProcessingParameterBand('autumn_correction_band', 'Autumn Correction band', parentLayerParameterName='autumn_correction_layer', allowMultiple=False, defaultValue=1))
        self.addParameter(QgsProcessingParameterRasterLayer('winter_correction_layer', 'Winter Correction layer', defaultValue=None))
        self.addParameter(QgsProcessingParameterBand('winter_correction_band', 'Winter Correction band', parentLayerParameterName='winter_correction_layer', allowMultiple=False, defaultValue=1))
        self.addParameter(QgsProcessingParameterNumber('period_length', 'Period length', type=QgsProcessingParameterNumber.Integer, minValue=10, maxValue=200, defaultValue=80))


    def processAlgorithm(self, parameters: dict[str, Any], context: QgsProcessingContext, model_feedback: QgsProcessingFeedback) -> dict[str, Any]:
        # Use a multi-step feedback, so that individual child algorithm progress reports are adjusted for the
        # overall progress through the model
        feedback = QgsProcessingMultiStepFeedback(30, model_feedback)
        results = {}
        outputs = {}


        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}

        # Temp variables, translation of parameters
        pname = parameters['project_name']
        period = parameters['period_length']

        # PostgreSQL execute and load SQL(reference only)

        conns = QgsProviderRegistry.instance().providerMetadata('postgres').connections(False)
        dbCon = conns[parameters['database_connection']]
        sqltxt = TEMPLATE3.format( parameters['project_name'], parameters['cell_size'])
        feedback.pushInfo('Before PG project execute: ' + sqltxt)
#        res = dbCon.executeSql("SELECT ST_AsText(geom) AS wkt FROM tgv_data.tgv_projects WHERE project_id = '{}'".format( parameters['project_name']))
        res = dbCon.executeSql(sqltxt)
        wkt = res[0][0]
        feedback.pushInfo('After PG project execute - WKT for project: ' + str(wkt))

        temp = QgsVectorLayer("Polygon?crs=epsg:25832", "temp", "memory")
        dp_temp = temp.dataProvider()
        geom = QgsGeometry.fromWkt(wkt)
        feat = QgsFeature()
        feat.setGeometry(geom)
        dp_temp.addFeatures([feat])
        feedback.pushInfo('Project temp layer written')



        # PostgreSQL execute and load SQL
        #alg_params = {
        #    'DATABASE': parameters['database_connection'],
        #    'GEOMETRY_FIELD': 'geom',
        #    'ID_FIELD': 'project_id',
        #   'SQL': "SELECT * FROM tgv_data.tgv_projects WHERE project_id = '{}'".format( parameters['project_name'])
        #}
        #outputs['PostgresqlExecuteAndLoadSql'] = processing.run('qgis:postgisexecuteandloadsql', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        #feedback.setCurrentStep(2)
        #if feedback.isCanceled():
        #    return {}
        #
        ## Buffer
        #alg_params = {
        #    'DISSOLVE': False,
        #    'DISTANCE': 0,
        #    'END_CAP_STYLE': 0,  # Round
        #    'INPUT': outputs['PostgresqlExecuteAndLoadSql']['OUTPUT'],
        #    'JOIN_STYLE': 0,  # Round
        #    'MITER_LIMIT': 2,
        #    'SEGMENTS': 5,
        #    'SEPARATE_DISJOINT': False,
        #    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        #}
        #outputs['Buffer'] = processing.run('native:buffer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        n = 2
        for season in ['Spring', 'Summer', 'Autumn', 'Winter']:
            n =+ 1
            feedback.setCurrentStep(n)
            if feedback.isCanceled():
                return {}
            feedback.pushInfo('Season : ' + season)
    
            # Calculate expression
            alg_params = {
                'INPUT': QgsExpression("'t_' || replace(uuid('WithoutBraces'),'-','')").evaluate()
            }
            outputs['CalculateExpression'] = processing.run('native:calculateexpression', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
            tempt = outputs['CalculateExpression']['OUTPUT']
            feedback.pushInfo('Before clip ' + season)
    
            # Clip raster by mask layer
            alg_params = {
                'ALPHA_BAND': False,
                'CREATION_OPTIONS': None,
                'CROP_TO_CUTLINE': True,
                'DATA_TYPE': 0,  # Use Input Layer Data Type
                'EXTRA': None,
                'INPUT': parameters[season.lower()+'_correction_layer'],
                'KEEP_RESOLUTION': True,
                #'MASK': outputs['Buffer']['OUTPUT'],
                'MASK': temp,
                'MULTITHREADING': False,
                'NODATA': None,
                'SET_RESOLUTION': False,
                'SOURCE_CRS': 'ProjectCrs',
                'TARGET_CRS': 'ProjectCrs',
                'TARGET_EXTENT': None,
                'X_RESOLUTION': None,
                'Y_RESOLUTION': None,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            outputs['ClipRasterByMaskLayer'] = processing.run('gdal:cliprasterbymasklayer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo('After clip ' + season)

            n =+ 1
            feedback.setCurrentStep(n)
            if feedback.isCanceled():
                return {}
            feedback.pushInfo('Before fillnodata ' + season)
    
            # Fill NoData
            alg_params = {
                'BAND': parameters[season.lower()+'_correction_band'],
                'CREATION_OPTIONS': None,
                'DISTANCE': 10,
                'EXTRA': None,
                'INPUT': outputs['ClipRasterByMaskLayer']['OUTPUT'],
                'ITERATIONS': 0,
                'MASK_LAYER': None,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            outputs['FillNodata'] = processing.run('gdal:fillnodata', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo('After fillnodata ' + season)
    
            n =+ 1
            feedback.setCurrentStep(n)
            if feedback.isCanceled():
                return {}
            feedback.pushInfo('Before raster to polygon ' + season)
    
            # Raster pixels to polygons
            alg_params = {
                'FIELD_NAME': 'depth',
                'INPUT_RASTER': outputs['FillNodata']['OUTPUT'],
                'RASTER_BAND': 1,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            outputs['RasterPixelsToPolygons'] = processing.run('native:pixelstopolygons', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo('After raster to polygon ' + season)
    
            n =+ 1
            feedback.setCurrentStep(n)
            if feedback.isCanceled():
                return {}
            feedback.pushInfo('Before extract by location ' + season)
    
            # Extract by location
            alg_params = {
                'INPUT': outputs['RasterPixelsToPolygons']['OUTPUT'],
            #    'INTERSECT': outputs['Buffer']['OUTPUT'],
                'INTERSECT': temp,
                'PREDICATE': [0],  # intersect
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            outputs['ExtractByLocation'] = processing.run('native:extractbylocation', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo('After extract by location ' + season)
    
            n =+ 1
            feedback.setCurrentStep(n)
            if feedback.isCanceled():
                return {}

            feedback.pushInfo('Before refactor fields ' + season)
            feedback.pushInfo('season = ' + season)
            feedback.pushInfo('pname  = ' + pname)
    
            # Refactor fields
            alg_params = {
                'FIELDS_MAPPING': [{'alias': '','comment': '','expression': ' round(x(centroid(@geometry)))*10000000 + round(y(centroid(@geometry)))','length': 0,'name': 'id','precision': 0,'sub_type': 0,'type': 4,'type_name': 'int8'},{'alias': '','comment': '','expression': '"depth"','length': 20,'name': 'depth','precision': 8,'sub_type': 0,'type': 6,'type_name': 'double precision'},{'alias': '','comment': '','expression': "'" + pname + "'",'length': 0,'name': 'project_id','precision': 0,'sub_type': 0,'type': 10,'type_name': 'text'},{'alias': '','comment': '','expression': "'"+season + "'",'length': 0,'name': 'season','precision': 0,'sub_type': 0,'type': 10,'type_name': 'text'}],
                'INPUT': outputs['ExtractByLocation']['OUTPUT'],
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            outputs['RefactorFields'] = processing.run('native:refactorfields', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo('After refactor fields ' + season)
    
            n =+ 1
            feedback.setCurrentStep(n)
            if feedback.isCanceled():
                return {}
            feedback.pushInfo('Before export to PG ' + season + ' '  + tempt)
    
            # Export to PostgreSQL
            alg_params = {
                'CREATEINDEX': True,
                'DATABASE': parameters['database_connection'],
                'DROP_STRING_LENGTH': False,
                'ENCODING': 'UTF-8',
                'FORCE_SINGLEPART': True,
                'GEOMETRY_COLUMN': 'geom',
                'INPUT': outputs['RefactorFields']['OUTPUT'],
                'LOWERCASE_NAMES': True,
                'OVERWRITE': True,
                'PRIMARY_KEY': 'id',
                'SCHEMA': 'tgv_import',
                'TABLENAME': tempt
            }
            outputs['ExportToPostgresql'] = processing.run('native:importintopostgis', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo('After export to PG ' + season + ' '  + tempt)
        
            n =+ 1
            feedback.setCurrentStep(n)
            if feedback.isCanceled():
                return {}

            # PostgreSQL execute SQL
            sqltxt = TEMPLATE.format(tempt)
            feedback.pushInfo('Before PG execute ' + season + ' '  + sqltxt)

            alg_params = {
                'DATABASE': parameters['database_connection'],
                'SQL': sqltxt
            }
            outputs['PostgresqlExecuteSql'] = processing.run('native:postgisexecutesql', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo('After PG execute ' + season)

            n =+ 1
            feedback.setCurrentStep(n)
            if feedback.isCanceled():
                return {}

            # PostgreSQL execute SQL
            sqltxt = TEMPLATE2.format(pname,period,season)
            feedback.pushInfo('Before PG2 execute ' + season + ' '  + sqltxt)

            alg_params = {
                'DATABASE': parameters['database_connection'],
                'SQL': sqltxt
            }
            outputs['PostgresqlExecuteSql'] = processing.run('native:postgisexecutesql', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo('After PG2 execute ' + season)

        return results

    def name(self) -> str:
        return 'terrain_groundwater_load_correction_data'

    def displayName(self) -> str:
        return 'OS2 Terrain Groundwater load correction data'

    def group(self) -> str:
        return ''

    def groupId(self) -> str:
        return ''

    def createInstance(self):
        return self.__class__()

