# -*- coding: utf-8 -*-

"""
/***************************************************************************
 TGVLoadDepthData
                                 A QGIS plugin
 QGIS processing plugin to load temporal correction data for hydrological 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-24
        copyright            : (C) 2026 by Bo Victor Thomsen AestasGIS Denmark
        email                : bvt@aestas.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Bo Victor Thomsen, AestasGIS Denmark'
__date__ = '2026-03-24'
__copyright__ = '(C) 2026 by Bo Victor Thomsen, AestasGIS Denmark'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

TEMPLATE = """
INSERT INTO tgv_data.tgv_corrections 
    SELECT project_id, season, id, depth, geom FROM tgv_import.{0} 
    ON CONFLICT ON CONSTRAINT tgv_corrections_pkey DO 
        UPDATE SET (geom,depth) = (EXCLUDED.geom,EXCLUDED.depth); 
DROP TABLE tgv_import.{0};
SELECT tgv_functions.cells_update_from_corrections('{1}',{2},'{3}');
"""

        #conns = QgsProviderRegistry.instance().providerMetadata('postgres').connections(False)
        #dbCon = conns['tgv_18 on localhost 5435']
        #dbUri = QgsDataSourceUri(dbCon.uri())
        #print(dbUri.host())
        #print(dbUri.port())
        #print(dbUri.username())
        #print(dbUri.password())
        #print(dbUri.database())
        #temp = QgsVectorLayer("Polygon?crs=epsg:25832", "temp", "memory")
        #dp_temp = temp.dataProvider()
        #geom = QgsGeometry.fromWkt(wkt)
        #feat = QgsFeature()
        #feat.setGeometry(geom)
        #dp_temp.addFeatures([feat])

from typing import Any, Optional

from qgis.core import QgsProcessing
from qgis.core import QgsProcessingAlgorithm
from qgis.core import QgsProcessingContext
from qgis.core import QgsProcessingFeedback, QgsProcessingMultiStepFeedback
from qgis.core import QgsProcessingParameterString
from qgis.core import QgsProcessingParameterFile
from qgis.core import QgsProcessingParameterDefinition
from qgis.core import QgsProcessingParameterCrs
from qgis.core import QgsProcessingParameterProviderConnection
from qgis.core import QgsProcessingParameterRasterLayer
from qgis.core import QgsProcessingParameterBand
from qgis.core import QgsProcessingParameterEnum
from qgis.core import QgsProcessingParameterNumber
from qgis.core import QgsProcessingParameterFeatureSink
from qgis.core import QgsExpression
from qgis.core import QgsProviderRegistry
from qgis.core import QgsDataSourceUri
from qgis import processing

#import rioxarray as rxr
import time
import os
import csv
import xarray as xr 
from sqlalchemy import create_engine, text
from io import StringIO
from osgeo import ogr, gdal
import json
import uuid

def psql_insert_copy(table, conn, keys, data_iter):
    dbapi_conn = conn.connection
    with dbapi_conn.cursor() as cur:

        s_buf = StringIO()
        writer = csv.writer(s_buf)
        writer.writerows(data_iter)
        s_buf.seek(0)

        columns = ', '.join('"{}"'.format(k) for k in keys)

        if table.schema:
            table_name = '"{}"."{}"'.format(table.schema, table.name)
        else:
            table_name = '"{}"'.format(table.name)

        sql = 'COPY {} ({}) FROM STDIN WITH CSV'.format(
            table_name, columns)
        cur.copy_expert(sql=sql, file=s_buf)

class TGVLoadDepthData(QgsProcessingAlgorithm):

    def initAlgorithm(self, config: Optional[dict[str, Any]] = None):
        self.addParameter(QgsProcessingParameterProviderConnection('database_connection', 'Database connection', 'postgres', defaultValue=None))
        self.addParameter(QgsProcessingParameterString('project_name', 'Project name', multiLine=False, defaultValue=None))
        self.addParameter(QgsProcessingParameterString('model_name', 'Model name', multiLine=False, defaultValue=None))
        self.addParameter(QgsProcessingParameterFile  ('netcfd_file', 'NetCFD file', behavior=QgsProcessingParameterFile.File, fileFilter='All Files (*.*)', defaultValue=None))
        self.addParameter(QgsProcessingParameterString('name_for_date_column', 'Name for "date" column', multiLine=False, defaultValue='time'))
        self.addParameter(QgsProcessingParameterString('name_for_x_value_column', 'Name for "x value" column', multiLine=False, defaultValue='X'))
        self.addParameter(QgsProcessingParameterString('name_for_y_value_column', 'Name for "y value" column', multiLine=False, defaultValue='Y'))
        self.addParameter(QgsProcessingParameterString('name_for_depth_column', 'Name for "depth" column', multiLine=False, defaultValue='depth to phreatic surface (negative)'))
        self.addParameter(QgsProcessingParameterNumber('cell_size', 'Cell size', type=QgsProcessingParameterNumber.Double, minValue=5, maxValue=1000, defaultValue=100))
        self.addParameter(QgsProcessingParameterCrs('coordinate_reference_system_espg_code', 'Coordinate Reference system (ESPG code)', defaultValue='EPSG:25832'))
        param = QgsProcessingParameterString('import_schema_name', 'Import schema name', multiLine=False, defaultValue='tgv_import')
        param.setFlags(param.flags() | QgsProcessingParameterDefinition.FlagAdvanced)
        self.addParameter(param)


    def processAlgorithm(self, parameters: dict[str, Any], context: QgsProcessingContext, model_feedback: QgsProcessingFeedback) -> dict[str, Any]:
        # Use a multi-step feedback, so that individual child algorithm progress reports are adjusted for the
        # overall progress through the model
        feedback = QgsProcessingMultiStepFeedback(10, model_feedback)
        results = {}
        outputs = {}

        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}

        # Create parameter group json 
        parameter_dict = {}
        parameter_dict['import_schema'] =parameters['import_schema_name']
        parameter_dict['import_date'] = parameters['name_for_date_column']
        parameter_dict['import_depth'] = parameters['name_for_depth_column']
        parameter_dict['import_x'] = parameters['name_for_x_value_column']
        parameter_dict['import_y'] = parameters['name_for_y_value_column']
        parameter_dict['cell_size'] = parameters['cell_size']
        parameter_dict['epsg_code'] = parameters['coordinate_reference_system_espg_code'].authid().replace('EPSG:','')

        # Calculate expression
        alg_params = {
            'INPUT': QgsExpression("'t_' || replace(uuid('WithoutBraces'),'-','')").evaluate()
        }
        outputs['CalculateExpression'] = processing.run('native:calculateexpression', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        parameter_dict['import_table'] = outputs['CalculateExpression']['OUTPUT']

        feedback.setCurrentStep(2)
        if feedback.isCanceled():
            return {}

        # Convert connection to sqlalchemy string
        conns = QgsProviderRegistry.instance().providerMetadata('postgres').connections(False)
        dbCon = conns[parameters['database_connection']]
        dbUri = QgsDataSourceUri(dbCon.uri())
        db_parameters = 'postgresql://{0}:{1}@{2}:{3}/{4}'.format(dbUri.username(),dbUri.password(),dbUri.host(),dbUri.port(),dbUri.database())
        # db_parameters = 'postgresql://postgres:ukulemy@localhost:5435/tgv_18'
        feedback.pushInfo('db_parameters = ' + db_parameters)
        feedback.pushInfo('project_name  = ' + parameters['project_name'])
        feedback.pushInfo('model_name    = ' + parameters['model_name'])

         
        # Fetch wkt from projects table
        res = dbCon.executeSql("SELECT ST_AsText(geom) AS wkt FROM tgv_data.tgv_projects WHERE project_id = '{}'".format( parameters['project_name']))
        wkt = res[0][0]

        # Fetch parameter group name fro models table.
        res = dbCon.executeSql("SELECT parameter_id FROM tgv_data.tgv_models WHERE project_id = '{0}' AND model_id = '{1}'".format(parameters['project_name'], parameters['model_name']))
        parameter_name = res[0][0]

        feedback.pushInfo('SqlAlchemy engine starting... ' + time.asctime())
        engine = create_engine(db_parameters)
        

        feedback.setCurrentStep(3)
        if feedback.isCanceled():
            return {}
        feedback.pushInfo('Open NetCFD dataset... ' + time.asctime())
        ds = xr.open_dataset(parameters['netcfd_file'])

        feedback.setCurrentStep(4)
        if feedback.isCanceled():
            return {}
        feedback.pushInfo('Convert to Pandas dataframe... ' + time.asctime())
        df = ds.to_dataframe()

        feedback.setCurrentStep(5)
        if feedback.isCanceled():
            return {}
        feedback.pushInfo('Filter on xmin..xmax, ymin..ymax... ' + time.asctime())
        geom = ogr.CreateGeometryFromWkt(wkt)
        extent = geom.GetEnvelope()
        xcol = parameter_dict['import_x']
        ycol = parameter_dict['import_y']
        #--- extensions from envelope +/- cell_size
        xmi = extent[0] - parameter_dict['cell_size']  
        xma = extent[1] + parameter_dict['cell_size']  
        ymi = extent[2] - parameter_dict['cell_size']  
        yma = extent[3] + parameter_dict['cell_size']  
        
        filter = '{xcol} > {xmi} and {xcol} < {xma} and {ycol} > {ymi} and {ycol} < {yma}'.format(xcol=xcol,ycol=ycol,xmi=xmi,ymi=ymi,xma=xma,yma=yma)
        dff = df.query(filter)

        feedback.setCurrentStep(6)
        if feedback.isCanceled():
            return {}
        feedback.pushInfo('Import data... ' + time.asctime())
        dff.to_sql(parameter_dict['import_table'], engine, method=psql_insert_copy,schema=parameter_dict['import_schema'],if_exists='replace')

        with engine.connect() as conn:

            feedback.setCurrentStep(6)
            if feedback.isCanceled():
                return {}
            feedback.pushInfo('Creating project cells... ' + time.asctime())
        
            sql = "SELECT tgv_functions.parameter_groups_update('{}','{}',{})".format(parameter_name, json.dumps(parameter_dict),True)
            result = conn.execute(text(sql))

            sql = "SELECT tgv_functions.cells_create_from_project_parameter('{}','{}')".format(parameters['project_name'], parameter_name)
            result = conn.execute(text(sql))
        
            feedback.setCurrentStep(7)
            if feedback.isCanceled():
                return {}
            feedback.pushInfo('Importing raw data til project cell_values... ' + time.asctime())
            sql = "SELECT tgv_functions.cell_values_create_from_import('{}','{}')".format(parameters['project_name'],parameters['model_name'])
            result = conn.execute(text(sql))
        
            conn.commit()
            feedback.pushInfo('Ending... ' + time.asctime())
        return results

    def name(self) -> str:
        return 'terrain_groundwater_load_depth_data'

    def displayName(self) -> str:
        return 'OS2 Terrain Groundwater load depth data'

    def group(self) -> str:
        return ''

    def groupId(self) -> str:
        return ''

    def createInstance(self):
        return self.__class__()




